User.create(username: 'Vlezya', password: 'password')
User.create(username: 'Neepa', password: 'password')
User.create(username: 'Joose', password: 'password')
User.create(username: 'Hip', password: 'password')
User.create(username: 'Lose', password: 'password')
